project:
  type: website

website:
  title: "A Blog + Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects and posts
      - href: resume.qmd
        text: My CV
    right:
      - text: "About Me"
        href: about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    code-fold: true

editor: visual

